version: '3.8'

services:
  app:
    build: .
    container_name: secrets_box_app
    command:
      - /bin/bash
      - -c
      - |
        rm -rf tmp/pids
        bundle install
        bundle exec rails db:migrate
        bundle exec rails s -b '0.0.0.0'
    volumes:
      - ".:/secrets_box"
    ports:
      - "3000:3000"
    depends_on:
      - db_postgres
      - redis
    env_file: 
      - .env

  db_postgres:
    image: postgres:latest
    container_name: secrets_box_db
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file: 
      - .env
    

  redis:
    image: redis:latest
    container_name: secrets_box_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
